# Generated by Django 3.2.2 on 2022-12-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_servicio', models.CharField(max_length=50)),
                ('sucursal', models.CharField(choices=[('BOGOTA', 'BOGOTA'), ('MEDELLIN', 'MEDELLIN'), ('CALI', 'CALI'), ('BARRANQUILLA', 'BARRANQUILLA'), ('CARTAGENA', 'BARRANQUILLA'), ('PEREIRA', 'PEREIRA'), ('BUCARAMANGA', 'BUCARAMANGA')], max_length=70)),
                ('placa', models.CharField(max_length=10)),
                ('tipo_vehiculo', models.CharField(max_length=40)),
                ('entregas', models.IntegerField()),
            ],
        ),
    ]
