# Generated by Django 3.2.2 on 2022-12-06 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0006_alter_detalle_vehiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle',
            name='vehiculo',
        ),
        migrations.AlterField(
            model_name='detalle',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='operacion.facturacion'),
        ),
    ]
