# Generated by Django 3.2.2 on 2022-12-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0007_auto_20221206_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='factura_vehiculo',
            field=models.IntegerField(blank=True, null=True, verbose_name='FACTURA POR VEHICULO'),
        ),
    ]
