# Generated by Django 3.2.2 on 2022-12-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0008_alter_detalle_factura_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='os',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
