# Generated by Django 3.2.2 on 2022-12-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0010_alter_detalle_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('MOTORIZADO', 'MOTORIZADO'), ('CARRY', 'CARRY')], max_length=40),
        ),
    ]
