# Generated by Django 3.2.2 on 2022-12-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0011_alter_facturacion_tipo_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacion',
            name='sucursal',
            field=models.CharField(choices=[('BOGOTA', 'BOGOTA'), ('MEDELLIN', 'MEDELLIN'), ('CALI', 'CALI'), ('BARRANQUILLA', 'BARRANQUILLA'), ('CARTAGENA', 'CARTAGENA'), ('PEREIRA', 'PEREIRA'), ('BUCARAMANGA', 'BUCARAMANGA')], max_length=70),
        ),
    ]
