# Generated by Django 3.2.2 on 2022-12-13 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacion', '0012_alter_facturacion_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthDecadeBornListFilter',
            fields=[
                ('facturacion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operacion.facturacion')),
            ],
            bases=('operacion.facturacion',),
        ),
        migrations.AddField(
            model_name='facturacion',
            name='visitas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
