# Generated by Django 3.2.2 on 2021-08-23 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('M_solicitud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('talla', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True, verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Ropa',
                'verbose_name_plural': 'Ropa',
            },
        ),
        migrations.CreateModel(
            name='Dotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('Estado', models.CharField(choices=[('Entregado', 'ENTREGADO'), ('Disponible ', 'DISPONIBLE '), ('Utilizado ', 'UTILIZADO ')], max_length=12)),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dotacion.user')),
                ('Sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='M_solicitud.sucursal')),
                ('Talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dotacion.talla')),
            ],
            options={
                'verbose_name': 'Dotacion',
                'verbose_name_plural': 'Dotacion',
            },
        ),
    ]
