# Generated by Django 3.2.2 on 2021-09-22 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0002_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='t_dotacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dotacion.dotacion'),
            preserve_default=False,
        ),
    ]
