# Generated by Django 3.2.2 on 2021-07-29 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='dotacion',
            name='Estado',
            field=models.CharField(choices=[('Entregado', 'Entregado'), ('Disponible ', 'Disponible '), ('Utilizado ', 'Utilizado ')], default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dotacion',
            name='Producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dotacion.user'),
        ),
    ]
