# Generated by Django 3.2.2 on 2021-07-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0003_auto_20210729_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dotacion',
            name='Estado',
            field=models.CharField(choices=[('Entregado', 'ENTREGADO'), ('Disponible ', 'DISPONIBLE '), ('Utilizado ', 'UTILIZADO ')], max_length=12),
        ),
    ]
