# Generated by Django 3.2.2 on 2021-09-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0003_entrega_t_dotacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dotacion',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
