# Generated by Django 3.2.2 on 2022-09-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0005_auto_20220912_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='dotacion',
            name='promedio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
