# Generated by Django 3.2.2 on 2022-09-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0008_alter_factura_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
