# Generated by Django 3.2.2 on 2022-09-14 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0012_auto_20220914_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_factura',
            name='factura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dotacion.factura'),
            preserve_default=False,
        ),
    ]
