# Generated by Django 3.2.2 on 2022-09-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0014_remove_factura_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='total',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='valor_unidad',
        ),
        migrations.AddField(
            model_name='producto_factura',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto_factura',
            name='valor_unidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
