# Generated by Django 3.2.2 on 2022-09-14 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0016_auto_20220914_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_factura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura_k', to='dotacion.factura'),
        ),
    ]
