# Generated by Django 3.2.2 on 2022-09-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0017_alter_producto_factura_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='total_factura',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
