# Generated by Django 3.2.2 on 2022-09-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0019_alter_producto_factura_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_factura',
            name='total',
            field=models.IntegerField(blank=True, null=True, verbose_name='subtotal'),
        ),
    ]
