# Generated by Django 3.2.2 on 2022-09-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0020_alter_producto_factura_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dotacion',
            name='cantidad',
            field=models.PositiveIntegerField(verbose_name='stock'),
        ),
    ]
