# Generated by Django 3.2.2 on 2022-09-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0021_alter_dotacion_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='dotacion',
            name='stock_usado',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
