# Generated by Django 3.2.2 on 2022-09-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0023_auto_20220915_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dotacion',
            old_name='total',
            new_name='total_dotacion',
        ),
    ]
