# Generated by Django 3.2.2 on 2022-09-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0024_rename_total_dotacion_total_dotacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dotacion',
            name='Estado',
        ),
        migrations.AlterField(
            model_name='dotacion',
            name='total_dotacion',
            field=models.IntegerField(verbose_name='total disponible'),
        ),
        migrations.DeleteModel(
            name='Devolucion',
        ),
    ]
