# Generated by Django 3.2.2 on 2022-09-15 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0025_auto_20220915_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('dotacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dotacion.dotacion')),
            ],
        ),
    ]
