# Generated by Django 3.2.2 on 2022-09-15 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0027_devolucion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dotacion',
            name='Producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dotacion.user', verbose_name='dotacion_ropa'),
        ),
    ]
