# Generated by Django 3.2.2 on 2022-09-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0028_alter_dotacion_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='total_factura',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
