# Generated by Django 3.2.2 on 2022-09-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0029_alter_factura_total_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='total_factura',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
