# Generated by Django 3.2.2 on 2022-09-19 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0031_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dotacion.tipo'),
        ),
    ]
