# Generated by Django 3.2.2 on 2022-09-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0032_user_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categoria'},
        ),
    ]
