# Generated by Django 3.2.2 on 2022-09-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0033_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dotacion',
            name='valor_promedio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
