# Generated by Django 3.2.2 on 2022-09-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0034_dotacion_valor_promedio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dotacion',
            name='promedio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dotacion',
            name='stock_usado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dotacion',
            name='total_dotacion',
            field=models.IntegerField(default=0, verbose_name='total disponible'),
        ),
        migrations.AlterField(
            model_name='dotacion',
            name='valor_promedio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
