# Generated by Django 3.2.2 on 2022-09-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0035_auto_20220924_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dotacion',
            name='cantidad',
            field=models.PositiveIntegerField(default=0, verbose_name='stock'),
        ),
    ]
