# Generated by Django 3.2.2 on 2022-09-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0036_alter_dotacion_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='total_unidades',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
