# Generated by Django 3.2.2 on 2022-09-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0037_factura_total_unidades'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dotacion',
            unique_together={('Producto', 'Talla')},
        ),
    ]
