# Generated by Django 3.2.2 on 2022-09-27 17:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0039_alter_factura_total_unidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 9, 27, 17, 44, 36, 665158, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
