# Generated by Django 3.2.2 on 2022-10-19 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0043_remove_entrega_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_factura',
            name='dotacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dotacion_detalle', to='dotacion.dotacion'),
        ),
    ]
