# Generated by Django 3.2.2 on 2022-12-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0044_alter_producto_factura_dotacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='tipo_devolucion',
            field=models.CharField(choices=[('1', 'Nuevo'), ('2', 'Usado')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dotacion',
            name='stock_usado',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
