# Generated by Django 3.2.20 on 2023-08-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotacion', '0045_auto_20221216_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='Valor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
