# Generated by Django 3.2.2 on 2021-05-18 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Periodo', models.CharField(choices=[('EN', 'Enero'), ('FE', 'Febrero'), ('MAR', 'Marzo'), ('ABR', 'Abril'), ('MAY', 'Mayo'), ('JUN', 'Junio'), ('JUL', 'Julio'), ('AGO', 'Agosto'), ('SEP', 'Septiembre'), ('OCT', 'Octubre'), ('NOV', 'Nomviembre'), ('DIC', 'Diciembre')], max_length=6)),
                ('Año', models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', ''), ('2024', ''), ('2025', '')], max_length=4)),
                ('meta', models.IntegerField()),
                ('limite', models.IntegerField(verbose_name='limite superior')),
                ('aspectos', models.TextField(max_length=100, verbose_name='Aspectos a destacar del mes')),
                ('solicitud', models.TextField(max_length=100, verbose_name='Solicitudes de recursos')),
                ('Tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.tipo_indicador')),
            ],
        ),
    ]
