# Generated by Django 3.2.2 on 2021-05-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='Porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
