# Generated by Django 3.2.2 on 2021-06-03 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicador',
            options={'verbose_name': 'Indicador', 'verbose_name_plural': 'Indicadores'},
        ),
        migrations.AlterModelOptions(
            name='tipo_indicador',
            options={'verbose_name': 'Tipo de indicador', 'verbose_name_plural': 'Tipo de indicadores'},
        ),
    ]
