# Generated by Django 3.2.2 on 2021-05-14 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indicadores', '0002_remove_indicador_dependencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='dependencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
