# Generated by Django 3.2.2 on 2021-05-14 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_dependencia_dependencia'),
        ('indicadores', '0003_indicador_dependencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='dependencia',
        ),
        migrations.RemoveField(
            model_name='indicador',
            name='id',
        ),
        migrations.AddField(
            model_name='indicador',
            name='place',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.dependencia'),
            preserve_default=False,
        ),
    ]
