# Generated by Django 3.2.2 on 2021-05-14 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0004_auto_20210514_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='indicador',
            name='Tipo',
            field=models.ForeignKey(default=40, on_delete=django.db.models.deletion.CASCADE, to='indicadores.tipo_indicador'),
            preserve_default=False,
        ),
    ]
