# Generated by Django 3.2.2 on 2021-05-14 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0005_auto_20210514_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicador',
            old_name='place',
            new_name='Dependencia',
        ),
    ]
