# Generated by Django 3.2.2 on 2021-05-14 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0007_estado_pedido_papeleria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido_papeleria',
            name='Area_s',
        ),
        migrations.AlterField(
            model_name='pedido_papeleria',
            name='Estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicadores.tipo_indicador'),
        ),
        migrations.AlterField(
            model_name='pedido_papeleria',
            name='can_pape',
            field=models.IntegerField(verbose_name='cantidad papeleria'),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
