# Generated by Django 3.2.2 on 2021-05-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dependencia', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Dependencia',
            field=models.ManyToManyField(to='users.dependencia'),
        ),
    ]
