# Generated by Django 3.2.2 on 2021-05-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210513_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Area',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administracion'), ('COMER', 'Comercial'), ('GH', 'Gestion_humana'), ('OPER', 'Operaciones'), ('ORG_M', 'Organización y metodos'), ('SE_NA', 'Seguridad_nacional'), ('SER_CL', 'servicio_al_cliente'), ('SIG', 'Sig'), ('TECNO', 'Tecnologia')], max_length=6),
        ),
    ]
