# Generated by Django 3.2.2 on 2021-05-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependencia',
            name='dependencia',
        ),
    ]
