# Generated by Django 3.2.2 on 2021-05-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_dependencia_dependencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencia',
            name='dependencia',
            field=models.CharField(default=7894, max_length=30),
            preserve_default=False,
        ),
    ]
