# Generated by Django 3.2.2 on 2021-05-21 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Articulo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hardware', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='inmobiliario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=20)),
                ('Descripcion', models.CharField(max_length=20)),
                ('Piso', models.IntegerField()),
                ('Observacion', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=45)),
                ('software', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serial', models.CharField(max_length=30)),
                ('Estado', models.BooleanField(default=False)),
                ('Observacion', models.TextField(max_length=50)),
                ('Licencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.licencia')),
                ('Marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.marcas')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.hardware', verbose_name='Hardware')),
            ],
        ),
    ]
