# Generated by Django 3.2.2 on 2021-05-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serial', models.CharField(max_length=30)),
                ('Producto', models.CharField(max_length=20)),
                ('Marca', models.CharField(max_length=18)),
                ('Estado', models.BooleanField(default=False)),
                ('Ubicacion', models.CharField(max_length=18)),
                ('Observacion', models.TextField(max_length=50)),
            ],
        ),
    ]
