# Generated by Django 3.2.2 on 2021-06-07 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='Ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.areas'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inmobiliario',
            name='Area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.areas'),
        ),
        migrations.AddField(
            model_name='inmobiliario',
            name='Articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.articulo'),
        ),
    ]
