# Generated by Django 3.2.2 on 2021-06-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='Disco',
            field=models.CharField(default=8, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='Hdmi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventario',
            name='Mac',
            field=models.TextField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='Procesador',
            field=models.CharField(default=15, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='Ram',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='Usb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventario',
            name='Vga',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='Observacion',
            field=models.TextField(max_length=250),
        ),
    ]
