# Generated by Django 3.2.2 on 2021-05-16 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_inventario_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=18)),
                ('modelo', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='inventario',
            name='Marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.marcas'),
        ),
    ]
