# Generated by Django 3.2.2 on 2021-06-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmobiliario',
            name='Sede',
            field=models.CharField(blank=True, choices=[('Cali', 'Cali'), ('Barranquilla', 'Barranquilla'), ('Bucaramanga', 'Bucaramanga'), ('Bogota', 'Bogota'), ('Cartagena', 'Cartagena'), ('Medelin', 'Medelin'), ('Eje cafetero', 'Eje cafetero')], max_length=20),
        ),
    ]
