# Generated by Django 3.2.2 on 2021-06-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='Hardware',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='serial',
            field=models.CharField(max_length=45, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='marcas',
            name='marca',
            field=models.CharField(max_length=18, primary_key=True, serialize=False, unique=True),
        ),
    ]
