# Generated by Django 3.2.2 on 2021-05-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='Modelo',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='Licencia',
        ),
        migrations.AddField(
            model_name='inventario',
            name='Licencia',
            field=models.ManyToManyField(to='inventario.Licencia'),
        ),
    ]
