# Generated by Django 3.2.2 on 2021-06-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20210601_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='Mac',
            field=models.CharField(max_length=20),
        ),
    ]
