# Generated by Django 3.2.2 on 2021-06-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_inventario_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='Disco',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='Hdmi',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='Procesador',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='Ram',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='Usb',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='Vga',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
