# Generated by Django 3.2.2 on 2021-06-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_inmobiliario_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmobiliario',
            name='Sede',
            field=models.CharField(choices=[('Cali', 'Cali'), ('Barranquilla', 'Barranquilla'), ('Bucaramanga', 'Bucaramanga'), ('Bogota', 'Bogota'), ('Cartagena', 'Cartagena'), ('Medelin', 'Medelin'), ('Eje cafetero', 'Eje cafetero')], max_length=20),
        ),
    ]
