# Generated by Django 3.2.2 on 2021-06-03 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_inmobiliario_sede'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardware',
            options={'verbose_name': 'Hardware', 'verbose_name_plural': 'Hardware'},
        ),
        migrations.AlterModelOptions(
            name='inmobiliario',
            options={'verbose_name': 'Inventario Inmobiliario ', 'verbose_name_plural': 'Inventario Inmobiliarios'},
        ),
        migrations.AlterModelOptions(
            name='inventario',
            options={'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventario Tecnologia'},
        ),
    ]
