# Generated by Django 3.2.2 on 2021-06-01 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_inventario_in_cont'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='in_cont',
        ),
    ]
