# Generated by Django 3.2.2 on 2021-06-07 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cecos',
            fields=[
                ('Ceco', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Nom_ceco', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Ceco',
                'verbose_name_plural': 'Cecos',
            },
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('Clasificaciones', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(blank=True, choices=[('ESPER', 'Espera de aprobacion'), ('APRO', 'Aprobado'), ('RECHA', 'Rechazado')], max_length=6)),
                ('Observaciones', models.TextField(blank=True, max_length=100)),
                ('Fecha', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('Proveedores', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('Sucursal', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='pedido_papeleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ti_pape', models.CharField(max_length=30, verbose_name='tipo de papeleria')),
                ('can_pape', models.IntegerField(verbose_name='cantidad papeleria')),
                ('Estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='M_solicitud.estado')),
            ],
            options={
                'verbose_name': 'Pedido de papeleria',
                'verbose_name_plural': 'Pedido de papeleria',
            },
        ),
        migrations.CreateModel(
            name='m_solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_ingreso', models.DateField()),
                ('f_pago', models.DateField()),
                ('f_contabilidad', models.DateField()),
                ('Servicio', models.CharField(blank=True, max_length=60)),
                ('Compañia', models.CharField(blank=True, choices=[('Firstsource', 'Firstsource'), ('TSE', 'TSE'), ('CP', 'CP')], max_length=20)),
                ('Novedades', models.TextField(blank=True, max_length=150)),
                ('V_gasto', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('V_total', models.IntegerField()),
                ('Ceco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='M_solicitud.cecos')),
                ('Clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='M_solicitud.clasificacion')),
                ('Sucursal', models.ManyToManyField(to='M_solicitud.Sucursal')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='M_solicitud.proveedor')),
            ],
            options={
                'verbose_name': 'Matriz de compra',
                'verbose_name_plural': 'Matriz de compras',
            },
        ),
    ]
