# Generated by Django 3.2.2 on 2021-06-03 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('M_solicitud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seco',
            fields=[
                ('Seco', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='m_solicitud',
            name='Compañia',
            field=models.CharField(blank=True, choices=[('Firstsource', 'Cali'), ('TSE', 'TSE'), ('CP', 'CP')], max_length=20),
        ),
        migrations.AddField(
            model_name='m_solicitud',
            name='Servicio',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='m_solicitud',
            name='Seco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='M_solicitud.seco'),
        ),
    ]
