# Generated by Django 3.2.2 on 2021-06-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M_solicitud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cecos',
            name='Ceco',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='clasificacion',
            name='Clasificaciones',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='Proveedores',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='Sucursal',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
