# Generated by Django 3.2.2 on 2022-01-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M_solicitud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_solicitud',
            name='n_factura',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Numero de factura'),
        ),
    ]
