# Generated by Django 3.2.2 on 2021-06-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M_solicitud', '0002_auto_20210603_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='seco',
            name='Nom_seco',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='seco',
            name='Seco',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
