# Generated by Django 3.2.2 on 2021-05-13 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('M_solicitud', '0002_auto_20210513_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacion',
            name='Clasificaciones',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='m_solicitud',
            name='Clasificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='M_solicitud.clasificacion'),
        ),
    ]
