# Generated by Django 3.2.2 on 2021-06-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M_solicitud', '0003_auto_20210603_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_solicitud',
            name='Compañia',
            field=models.CharField(blank=True, choices=[('Firstsource', 'Firstsource'), ('TSE', 'TSE'), ('CP', 'CP')], max_length=20),
        ),
    ]
