# Generated by Django 3.2.2 on 2021-05-13 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('M_solicitud', '0003_auto_20210513_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Proveedores', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='m_solicitud',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='M_solicitud.proveedor'),
        ),
    ]
