# Generated by Django 3.2.2 on 2021-05-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M_solicitud', '0004_auto_20210513_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sucursal', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='clasificacion',
            name='Clasificaciones',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='m_solicitud',
            name='Sucursal',
            field=models.ManyToManyField(to='M_solicitud.Sucursal'),
        ),
    ]
