# Generated by Django 3.2.2 on 2021-06-03 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('M_solicitud', '0004_alter_m_solicitud_compañia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='m_solicitud',
            options={'verbose_name': 'Matriz de compra', 'verbose_name_plural': 'Matriz de compras'},
        ),
        migrations.AlterModelOptions(
            name='pedido_papeleria',
            options={'verbose_name': 'Pedido de papeleria', 'verbose_name_plural': 'Pedido de papeleria'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='seco',
            options={'verbose_name': 'Ceco', 'verbose_name_plural': 'Cecos'},
        ),
        migrations.AddField(
            model_name='m_solicitud',
            name='Novedades',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='m_solicitud',
            name='Seco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='M_solicitud.seco', verbose_name='Ceco'),
        ),
        migrations.AlterField(
            model_name='seco',
            name='Nom_seco',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ceco'),
        ),
        migrations.AlterField(
            model_name='seco',
            name='Seco',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Ceco'),
        ),
    ]
