# Generated by Django 3.2.2 on 2021-06-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M_solicitud', '0006_alter_m_solicitud_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_solicitud',
            name='iva',
            field=models.DecimalField(choices=[('0,19', '0,19'), ('1', '1')], decimal_places=2, max_digits=12),
        ),
    ]
