# Generated by Django 3.2.2 on 2021-06-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M_solicitud', '0010_alter_m_solicitud_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_solicitud',
            name='iva',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
