# Generated by Django 3.2.2 on 2021-06-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M_solicitud', '0011_alter_m_solicitud_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_solicitud',
            name='V_gasto',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='m_solicitud',
            name='V_total',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='m_solicitud',
            name='iva',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
