# Generated by Django 3.2.2 on 2021-06-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M_solicitud', '0012_auto_20210617_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_solicitud',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12),
        ),
    ]
