# Generated by Django 3.2.2 on 2021-06-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M_solicitud', '0014_alter_m_solicitud_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_solicitud',
            name='iva',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
