# Generated by Django 3.2.2 on 2021-06-21 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('M_solicitud', '0015_alter_m_solicitud_iva'),
    ]

    operations = [
        migrations.CreateModel(
            name='rep_conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_factura', models.CharField(max_length=30)),
                ('Proveedor', models.CharField(max_length=70)),
                ('Fecha', models.DateField()),
                ('Valor', models.DecimalField(decimal_places=0, max_digits=12)),
                ('Iva', models.DecimalField(decimal_places=0, max_digits=12)),
                ('Va_total', models.DecimalField(blank=True, decimal_places=0, max_digits=12)),
                ('Observaciones', models.TextField(max_length=100)),
                ('Ceco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='M_solicitud.cecos')),
            ],
        ),
    ]
