# Generated by Django 3.2.2 on 2021-06-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M_solicitud', '0016_rep_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rep_conta',
            name='Va_total',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True),
        ),
    ]
