# Generated by Django 3.2.2 on 2021-06-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M_solicitud', '0019_auto_20210621_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prov_cont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Proveedor', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores Contable',
            },
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores Compras'},
        ),
        migrations.AlterField(
            model_name='rep_costos',
            name='N_factura',
            field=models.CharField(max_length=30, verbose_name='Numero de factura'),
        ),
        migrations.AlterField(
            model_name='rep_costos',
            name='Va_total',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Valor total'),
        ),
    ]
