# Generated by Django 3.2.2 on 2021-06-22 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('M_solicitud', '0021_alter_rep_conta_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prov_cont',
            name='Proveedor',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rep_conta',
            name='Proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='M_solicitud.prov_cont'),
        ),
    ]
