# Generated by Django 3.2.2 on 2021-06-22 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('M_solicitud', '0023_alter_prov_cont_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rep_conta',
            name='Proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='M_solicitud.prov_cont'),
        ),
    ]
