# Generated by Django 3.2.2 on 2021-06-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M_solicitud', '0024_alter_rep_conta_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prov_cont',
            name='id',
        ),
        migrations.AlterField(
            model_name='prov_cont',
            name='Proveedor',
            field=models.CharField(default=1, max_length=30, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
