# Generated by Django 3.2.2 on 2021-06-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M_solicitud', '0025_auto_20210622_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prov_cont',
            name='Proveedor',
            field=models.CharField(blank=True, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
