# Generated by Django 3.2.2 on 2021-06-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M_solicitud', '0026_alter_prov_cont_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rep_conta',
            name='Proveedor',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
