# Generated by Django 3.2.2 on 2021-06-24 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('M_solicitud', '0027_alter_rep_conta_proveedor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prov_cont',
        ),
    ]
