# Generated by Django 3.2.2 on 2021-06-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('M_solicitud', '0029_alter_rep_costos_ceco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rep_conta',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rep_costos',
            options={},
        ),
    ]
