# Generated by Django 3.2.2 on 2021-06-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('M_solicitud', '0031_proveedor_nit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cecos',
            old_name='Ceco',
            new_name='id',
        ),
    ]
