# Generated by Django 3.2.2 on 2021-06-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M_solicitud', '0032_rename_ceco_cecos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cecos',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Ceco'),
        ),
    ]
