# Generated by Django 3.2.2 on 2021-07-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('M_solicitud', '0034_remove_m_solicitud_novedades'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_solicitud',
            name='Novedades',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
