# Generated by Django 3.2.2 on 2021-07-02 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('M_solicitud', '0035_m_solicitud_novedades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m_solicitud',
            name='Novedades',
        ),
    ]
