# Generated by Django 3.2.2 on 2021-08-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Cta', models.IntegerField()),
                ('D_C', models.CharField(max_length=2)),
                ('Identificacion', models.CharField(max_length=15)),
                ('Nombre', models.CharField(max_length=70)),
                ('Codigo', models.CharField(max_length=8)),
                ('Nombre_CC', models.CharField(max_length=20)),
                ('Concepto', models.CharField(max_length=40)),
                ('Valor', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Nomina',
                'verbose_name_plural': 'Nomina',
            },
        ),
        migrations.CreateModel(
            name='Seguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Identificacion', models.CharField(max_length=15)),
                ('Provision', models.CharField(max_length=20)),
                ('Cta', models.IntegerField()),
                ('D_C', models.CharField(max_length=1)),
                ('Valor', models.DecimalField(decimal_places=0, max_digits=12)),
                ('Nombre', models.CharField(max_length=60)),
                ('Centro_Costo', models.CharField(max_length=20)),
                ('Concepto', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Seguridad Social y Prestaciones',
                'verbose_name_plural': 'Seguridad Social y Prestaciones',
            },
        ),
    ]
