# Generated by Django 3.2.2 on 2021-06-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargue',
            old_name='Cuenta_Contable',
            new_name='Cantidad1',
        ),
        migrations.RenameField(
            model_name='cargue',
            old_name='Valor',
            new_name='Cantidad2',
        ),
        migrations.RenameField(
            model_name='cargue',
            old_name='Descripcion',
            new_name='Centro_Costo',
        ),
        migrations.RemoveField(
            model_name='cargue',
            name='Concepto',
        ),
        migrations.RemoveField(
            model_name='cargue',
            name='Fecha',
        ),
        migrations.RemoveField(
            model_name='cargue',
            name='Nombre',
        ),
        migrations.RemoveField(
            model_name='cargue',
            name='Tipo',
        ),
        migrations.AddField(
            model_name='cargue',
            name='A_inactividad',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Ajus_prima',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Ajuste_roda_neg',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Ajuste_roda_pos',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Ajustes_red_noc',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Apor_Pension',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Apor_salud',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Aux_Rodamiento',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Aux_alimentacion',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Aux_ex_transporte',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Aux_transporte',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Banco',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Bonificacion',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Cantidad3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Cantidad4',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Cantidad5',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Cantidad6',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Cantidad7',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Comisiones',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Consecutivo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Cuen_bancaria',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Cuota_sos_lec',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='D_Aportes_año',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='D_cred_f_e_beneficiar',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Des_prima',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Dias',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Dto_lentes',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Entregas_efec',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='F_E_Beneficiar',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Fon_solidaridad',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='G_transporte',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Hora_ex_dom_fes_con_com',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Hora_ex_dom_fes_sin_com',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Hora_ex_noc',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Inactividad',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Nom_completo',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='O_descuentos',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Poliza_vida',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Prima_ex_lega',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Prima_legal',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Recargo_noc',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Recargo_noc_fes',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Retencion_fuen',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Retroactivo',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Sal_integral',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Sueldo',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Tot_neto_pa',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Tot_neto_pa_com',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Total_descuentos',
            field=models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Total_devengado',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='cargue',
            name='Vacaciones',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='Vacaciones_plata',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='cuo_sos_produ',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='hora_ex_diur',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cargue',
            name='in_cesantias',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cargue',
            name='Identificacion',
            field=models.CharField(max_length=15),
        ),
    ]
