# Generated by Django 3.2.2 on 2021-05-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargue',
            name='Fecha',
            field=models.CharField(max_length=10),
        ),
    ]
