# Generated by Django 3.2.2 on 2021-06-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0002_auto_20210612_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargue',
            name='Total_devengado',
            field=models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
    ]
