# Generated by Django 3.2.2 on 2021-06-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0003_alter_cargue_total_devengado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargue',
            name='Total_descuentos',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
