# Generated by Django 3.2.2 on 2021-05-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0003_auto_20210526_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargue',
            name='Fecha',
            field=models.DateTimeField(max_length=10),
        ),
    ]
