# Generated by Django 3.2.2 on 2021-05-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0004_alter_cargue_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargue',
            name='Fecha',
            field=models.DateTimeField(),
        ),
    ]
