# Generated by Django 3.2.2 on 2021-05-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0006_alter_cargue_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargue',
            name='Cuenta_Contable',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cargue',
            name='Identificacion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cargue',
            name='Valor',
            field=models.IntegerField(),
        ),
    ]
