# Generated by Django 3.2.2 on 2021-06-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0007_seguridad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargue',
            options={'verbose_name': 'Nomina ', 'verbose_name_plural': 'Nomina'},
        ),
        migrations.AlterModelOptions(
            name='seguridad',
            options={'verbose_name': 'Seguridad Social', 'verbose_name_plural': 'Seguridad Social'},
        ),
        migrations.AlterField(
            model_name='seguridad',
            name='Fecha',
            field=models.CharField(max_length=11),
        ),
    ]
