# Generated by Django 3.2.2 on 2021-06-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0008_auto_20210616_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguridad',
            name='Fecha',
            field=models.DateField(),
        ),
    ]
