# Generated by Django 3.2.2 on 2021-06-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0009_alter_seguridad_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguridad',
            name='Valor',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
