# Generated by Django 3.2.2 on 2021-06-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0011_auto_20210621_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomina',
            options={},
        ),
    ]
