# Generated by Django 3.2.2 on 2021-06-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0012_alter_nomina_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='Fecha',
            field=models.DateField(),
        ),
    ]
