# Generated by Django 3.2.2 on 2021-06-21 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0013_alter_nomina_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomina',
            options={'verbose_name': 'Nomina', 'verbose_name_plural': 'Nomina'},
        ),
    ]
